version: '3.1'

services:
  db-postgresql:
    image: "postgres:14.3-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "dbpostgresql:/var/lib/postgresql/data"
volumes:
  dbpostgresql: null